### PR TITLE
Added OpenAPI definition

### PR DESCRIPTION
**Pull request by frikky**
Added base for an OpenAPI definition for TheHive.

### CODE REVIEW

**Comment by nadouani** [comment]
Yeeah this is a great contribution, I wasn't aware of it!!

**Comment by nadouani** [comment]
Do you plan to cover the rest of the APIs? Do you think it deserves a dedicated repo?

**Comment by frikky** [comment]
It definitely doesn't need a dedicated repo, but could be added to https://github.com/TheHive-Project/TheHiveDocs/tree/master/api (as this is where people go for TheHive API's usually), as well as a link to make it easier to explore the API (OpenAPI has tools for this). 

I will try to finish it before christmas sometime, but can't promise anything (it doesn't take that long to make, so ill try). 

Love this repo!!

**Comment by nadouani** [comment]
Sound great, feel free to submit a PR to `TheHiveDocs` repo, and we will invite people to contribute too ;)

Thanks for you work

**Pull request merged**
